export const navBarOptions = [
  {
    id: 1,
    name: "Option 1",
  },
  {
    id: 2,
    name: "Option 2",
  },
  {
    id: 3,
    name: "Option 3",
  },
  {
    id: 4,
    name: "Option 4",
  },
  {
    id: 5,
    name: "Option 5",
  },
];
export const DaysOptions = [
  {
    id: 1,
    name: "Last 2 Days",
  },
  {
    id: 2,
    name: "Last 7 Days",
  },
  {
    id: 3,
    name: "Last 30 Days",
  },
  {
    id: 4,
    name: "Last 6 Months",
  },
  {
    id: 5,
    name: "Last 1 Year",
  },
];
export const category = [
  {
    id: 1,
    name: "CSPM",
    content: [
      "Widget 1",
      "Widget 2",
      "Widget 3",
      "Widget 4",
      "Widget 5",
      "Widget 6",
      "Widget 7",
      "Widget 8",
      "Widget 9",
      "Widget 10",
      "Widget 11",
      "Widget 12",
      "Widget 13",
      "Widget 14",
      "Widget 15",
      "Widget 16",
      "Widget 17",
      "Widget 18",
      "Widget 19",
      "Widget 20",
    ],
  },
  {
    id: 2,
    name: "CWPP",
    content: [
      "Widget 21",
      "Widget 22",
      "Widget 23",
      "Widget 24",
      "Widget 25",
      "Widget 26",
      "Widget 27",
      "Widget 28",
      "Widget 29",
      "Widget 30",
      "Widget 31",
      "Widget 32",
      "Widget 33",
      "Widget 34",
      "Widget 35",
      "Widget 36",
      "Widget 37",
      "Widget 38",
      "Widget 39",
      "Widget 40",
    ],
  },
  {
    id: 3,
    name: "CIEM",
    content: [
      "Widget 41",
      "Widget 42",
      "Widget 43",
      "Widget 44",
      "Widget 45",
      "Widget 46",
      "Widget 47",
      "Widget 48",
      "Widget 49",
      "Widget 50",
      "Widget 51",
      "Widget 52",
      "Widget 53",
      "Widget 54",
      "Widget 55",
      "Widget 56",
      "Widget 57",
      "Widget 58",
      "Widget 59",
      "Widget 60",
    ],
  },
  {
    id: 4,
    name: "SOAR",
    content: [
      "Widget 61",
      "Widget 62",
      "Widget 63",
      "Widget 64",
      "Widget 65",
      "Widget 66",
      "Widget 67",
      "Widget 68",
      "Widget 69",
      "Widget 70",
      "Widget 71",
      "Widget 72",
      "Widget 73",
      "Widget 74",
      "Widget 75",
      "Widget 76",
      "Widget 77",
      "Widget 78",
      "Widget 79",
      "Widget 80",
    ],
  },
  {
    id: 5,
    name: "SIEM",
    content: [
      "Widget 81",
      "Widget 82",
      "Widget 83",
      "Widget 84",
      "Widget 85",
      "Widget 86",
      "Widget 87",
      "Widget 88",
      "Widget 89",
      "Widget 90",
      "Widget 91",
      "Widget 92",
      "Widget 93",
      "Widget 94",
      "Widget 95",
      "Widget 96",
      "Widget 97",
      "Widget 98",
      "Widget 99",
      "Widget 100",
    ],
  },
];

export const ChartData = [
  {
    heading: "Cloud Account 1",
    content: [
      { color: "#dc2626", text: "Failed", num: 50 },
      { color: "#16a34a", text: "Passed", num: 80 },
      { color: "#f59e0b", text: "In Progress", num: 21 },
      { color: "black", text: "Not Available", num: 40 },
      { color: "#3b82f6", text: "Compliant", num: 60 },
    ],
  },
  {
    heading: "Security Compliance 2",
    content: [
      { color: "#3b82f6", text: "Compliant", num: 60 },
      { color: "#ef4444", text: "Non-Compliant", num: 30 },
      { color: "#10b981", text: "Pending", num: 10 },
      { color: "black", text: "Not Available", num: 40 },
    ],
  },
];

export const splinedata = [
  {
    name: "Page A",
    uv: 4000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: "Page B",
    uv: 3000,
    pv: 1398,
    amt: 2210,
  },
  {
    name: "Page C",
    uv: 2000,
    pv: 9800,
    amt: 2290,
  },
  {
    name: "Page D",
    uv: 2780,
    pv: 3908,
    amt: 2000,
  },
  {
    name: "Page E",
    uv: 1890,
    pv: 4800,
    amt: 2181,
  },
  {
    name: "Page F",
    uv: 2390,
    pv: 3800,
    amt: 2500,
  },
  {
    name: "Page G",
    uv: 3490,
    pv: 4300,
    amt: 2100,
  },
];